/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "yrkrxfonzctufoejqtpf"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlya3J4Zm9uemN0dWZvZWpxdHBmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIyMjM0NzMsImV4cCI6MjA4Nzc5OTQ3M30.TKfgWPxq-RXIQ9VOAVWYWkOXuArd6bw-7iCkLW1iDcw"